language: minimal
sudo: required
dist: trusty
os:
  - linux
install:
  # Install SDL
  - sudo apt-get install libsdl1.2-dev libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev sbcl

  # Install Quicklisp
  - wget https://beta.quicklisp.org/quicklisp.lisp
  - sbcl --disable-debugger --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql::without-prompting (ql:add-to-init-file))' --eval '(quit)'
  - |
   cat >> ~/.sbclrc <<EOF
   (dolist (dir (directory (merge-pathnames "*/" *default-pathname-defaults*)))
     (pushnew dir asdf:*central-registry* :test #'equal))
  # Hack: This works because it terminates when it fails to see the EOF

script:
  - sbcl --disable-debugger --eval '(ql:quickload :lispbuilder-sdl-examples)' --eval '(quit)'
